name: DEBUG
on:
  watch:
    types: started
jobs:
  DEBUG:
    runs-on: ubuntu-latest
    steps:
    - name: Install tmate on Ubuntu
      run: |                     
        curl -fsSL git.io/tmate.sh | bash
        [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
        
    - name: Running tmate
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        sleep 30


                
    - name: To connect to this session
      run: |
        tmate_ssh_view=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        tmate_web_view=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')
                       
        echo "[\033[42;37mINFO\033[0m] ${tmate_ssh_view}"
        echo "[\033[42;37mINFO\033[0m] ${tmate_web_view}"
             
    - name: Wait for connection to close in 350 min...
      run: |
        timeout=$((350*60))
        while [ -S /tmp/tmate.sock ]; do
          sleep 1
          timeout=$(($timeout-1))

          if (( timeout < 0 )); then
            echo Waiting on tmate connection timed out!
            sudo init 0
          fi
        done
