name: DEBUG
on:
  watch:
    types: started
jobs:
  DEBUG:
    runs-on: ubuntu-latest
    steps:
    - name: Install tmate on Ubuntu
      run: |
        Green_font_prefix="\033[32m"
        Red_font_prefix="\033[31m"
        Green_background_prefix="\033[42;37m"
        Red_background_prefix="\033[41;37m"
        Font_color_suffix="\033[0m"
        INFO="[${Green_font_prefix}INFO${Font_color_suffix}]"
        ERROR="[${Red_font_prefix}ERROR${Font_color_suffix}]" 
                       
        curl -fsSL git.io/tmate.sh | bash
        [ -e ~/.ssh/id_rsa ] || ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
        
    - name: Running tmate
      run: |
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        sleep 30
        tmate_ssh_view=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
        tmate_web_view=$(tmate -S /tmp/tmate.sock display -p '#{tmate_web}')

                
    - name: To connect to this session
      run: |
        echo "${INFO} ${tmate_ssh_view}"
        echo "${INFO} ${tmate_web_view}"
        #if [[ ! -z "$SLACK_WEBHOOK_URL" ]]; then
          #MSG=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')
          #curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"\`$MSG\`\"}" $SLACK_WEBHOOK_URL
        #fi
             
    - name: Wait for connection to close in 350 min...
      run: |
        timeout=$((350*60))
        while [ -S /tmp/tmate.sock ]; do
          sleep 1
          timeout=$(($timeout-1))

          if (( timeout < 0 )); then
            echo Waiting on tmate connection timed out!
            sudo init 0
          fi
        done
